on:
  workflow_dispatch:
  push:
    paths:
      - '*.c'
      - '*.h'
      - '.github/workflows/tests.yml'
  release:
    types: [published]
    
permissions:
  contents: write
  pages: write      # to deploy to Pages
  id-token: write   # to verify the deployment originates from an appropriate source

jobs:
  build:
    runs-on: ubuntu-20.04
    
    env:
      PROJECT_NAME: ${{ github.event.repository.name }} 
    steps:
    - name: Checkout this repo
      uses: actions/checkout@master
      with:
        path: ${{ env.PROJECT_NAME }}
    
    - name: Setup Environment
      run: | 
        sudo apt-get update -qq
        sudo apt-get install -y --no-install-recommends python3 python3-pip
        sudo pip3 install gcovr
        mkdir ${{ env.PROJECT_NAME }}/report
        ls ${{ env.PROJECT_NAME }}
      shell: bash

    - name: Build Product
      run: |
        cd ${{ env.PROJECT_NAME }}
        gcc -fPIC -fprofile-arcs -ftest-coverage -o test test.c
    
    - name: Run tests
      run: |
        cd ${{ env.PROJECT_NAME }}
        ./test
        gcov test.c
        gcovr --root . --html --html-details --output report/coverage.html

    - name: upload artifact
      uses: actions/upload-pages-artifact@v3
      id: deployment
      with: 
        path: ${{ env.PROJECT_NAME }}/report/

  deploy:
    needs: build
    runs-on: ubuntu-20.04
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: deploy to Github Pages
        uses: actions/deploy-pages@v3
        id: deployment
